#!/usr/bin/python

# IVLE - Informatics Virtual Learning Environment
# Copyright (C) 2007-2008 The University of Melbourne
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# Script: fileservice
# Author: Matt Giuca
# Date:   5/2/2007

# A CGI script for handling file requests. This is a wrapper around the
# FileService library module. It is intended to be run from the trampoline by
# the FileService application.
# (The purpose of all of this is to let FileService read and write the user's
# file system as them).

from common import cgirequest
import fileservice_lib

# Use a CGIRequest object to make the CGI environment look like the normal
# IVLE handler environment. This lets us call FileService as if it were an
# IVLE app.

req = cgirequest.CGIRequest()
req.install_error_handler()
fileservice_lib.handle(req)
