#!/usr/bin/python

# IVLE - Informatics Virtual Learning Environment
# Copyright (C) 2008 The University of Melbourne
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# Script: logservice
# Author: William Grant
# Date:   08/07/2008

# A CGI script for viewing a Subversion log. Used by the svnlog app.

import os
import time
import pysvn

from common import cgirequest

req = cgirequest.CGIRequest()
req.content_type = "text/html"

req.write('<h1>Subversion Log</h1>\n')


def pretty_time(epochtime):
    return time.asctime(time.localtime(epochtime))

def pretty_path(path):
    return '%s %s' % (path['action'], path['path'])

def pretty_paths(paths):
    output = '<ul>'
    for path in paths:
        output += '<li>' + pretty_path(path) + '</li>'
    output += '</ul>'
    return output

def pretty_log(log):
    return '''
<div class="svnlogentry">
	<div class="svnloginfo">
		Revision <strong>%d</strong> by <strong>%s</strong> on <strong>%s</strong>
	</div>
	<pre>%s</pre>
        <hr size="1"/>
        <h2>Changed paths:</h2>
        <div class="svnlogpathlist">
	%s
        </div>
</div>''' % (log.revision.number, log.author, pretty_time(log.date),
             log.message, pretty_paths(log.changed_paths))

try:
    client = pysvn.Client()
    logs = client.log(os.path.join('/home', req.path), discover_changed_paths=True)
    [req.write(pretty_log(log)) for log in logs]
except pysvn.ClientError, e:
    req.write('<p><b>Error:</b></p>\n')
    req.write('<pre>%s</pre>\n' % cgi.escape(str(e)))
