#!/usr/bin/python

# IVLE - Informatics Virtual Learning Environment
# Copyright (C) 2008 The University of Melbourne
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# Script: logservice
# Author: William Grant
# Date:   08/07/2008

# A CGI script for viewing a Subversion log. Used by the svnlog app.

import os
import time
import cgi
import pysvn

import common.cgirequest
import common.util
import common.date

req = common.cgirequest.CGIRequest()
req.install_error_handler()
req.content_type = "text/html"

req.write('<h1>Subversion Log</h1>\n')


def pretty_path(cpath, revno=None):
    path = cpath['path']
    # XXX: We can't assume that the repository root is always equivalent to
    #      the current user's home directory, although it does work for our
    #      current setup.
    url = common.util.make_path(os.path.join('files',
                                    common.util.split_path(req.path)[0],
                                    path[1:]))
    if revno:
        url += '?r=%d' % revno
    return '%s <a href="%s">%s</a>' % (cpath['action'], cgi.escape(url, True),
                                       cgi.escape(path))

def pretty_paths(paths, revno=None):
    output = '<ul>'
    for path in paths:
        output += '<li>' + pretty_path(path, revno) + '</li>'
    output += '</ul>'
    return output

def pretty_log(log):
    return '''
<div class="svnlogentry">
	<div class="svnloginfo">
		Revision <a href="%s?r=%d" style="font-weight: bold">%d</a>
		by <strong>%s</strong> on <strong>%s</strong>
	</div>
	<pre>%s</pre>
        <hr size="1"/>
        <h2>Changed paths:</h2>
        <div class="svnlogpathlist">
	%s
        </div>
</div>''' % (cgi.escape(common.util.make_path(os.path.join('files', req.path))),
             log.revision.number, log.revision.number, cgi.escape(log.author),
             common.date.make_date_nice(log.date), cgi.escape(log.message),
             pretty_paths(log.changed_paths, log.revision.number))

try:
    client = pysvn.Client()
    logs = client.log(os.path.join('/home', req.path), discover_changed_paths=True)
    [req.write(pretty_log(log)) for log in logs]
except pysvn.ClientError, e:
    req.write('<p><b>Error:</b></p>\n')
    req.write('<pre>%s</pre>\n' % cgi.escape(str(e)))
